apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spark-worker-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: spark-worker
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
